services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server/src:/app/src
    environment:
      - DB_HOST=mysql
      - DB_PASSWORD=password
      - DB_NAME=data_viento_database
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: data_viento_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/db:/docker-entrypoint-initdb.d
  web:
    build: ./web
    container_name: caddy_server
    ports:
      - "80:80"
volumes:
  db_data:
